import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { redirect } from "next/navigation";

export default function Game() {
  const { data: sessionData } = useSession();


  console.log(sessionData);

  if (sessionData == undefined) {
    console.log("sessionData is undefined");
    // () => void signIn();
    redirect("/");
  }

  return (
    <>
      <Head>
        <title>Monopoly Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Monopoly Game
        </h1>

        {sessionData ? (
          <>
            <span>Logged in as {sessionData.user?.name}</span>
            <button onClick={() => void signOut()}> logout</button>
          </>
        ) : (
          <span>Not logged in</span>
        )}

        {/* <AuthShowcase /> */}
      </main>
    </>
  );
}
